### ISSUE TITLE
最后观看OB视频提示。。。。

### ISSUE THREAD

**Issue by donqee** [tzwsoho/LOLOBCrawler#1]
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at D:\腾讯游戏\英雄联盟\launch.js:30:10
    at Object.<anonymous> (D:\腾讯游戏\英雄联盟\launch.js:60:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by donqee** [comment]
已经解决，但是TP和谐无法进入LOL观看

**Comment by tzwsoho** [comment]
嗯，应该不是TP问题，是OB的格式变了，过段时间有空我再研究下新的算法

**Comment by donqee** [comment]
呃呃呃，我说到底什么情况。。。。

**Comment by tzwsoho** [comment]
最近版本更新比较频繁，但是我发现只要TGP可以观战的时候我的爬虫都可以观战，估计真如你所说是TP禁用了OB功能
